---
- name: Workstation
  hosts: 
    - localhost
  roles:
  tasks:
  - name: Install all packages
    ansible.builtin.package:
      name:
        - pam_kwallet
        - plasma5-workspace-wallpapers
      state: latest
    become: true
    tags: packages
